adminUser:
  password: vault:dconde-cjxd34-ga/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dconde@cloudbees.com
  token: vault:dconde-cjxd34-ga/pipelineUser:token
  username: daveconde
prow:
  hmacToken: vault:dconde-cjxd34-ga/prow:hmacToken
